
INSERT INTO public.consultants (name, title, image_url, competences, industries, experience_years, location, description, sort_order) VALUES
('Kacper Wysocki', NULL, NULL, ARRAY['Embedded Linux','RTOS','Security','Firmware','CI/CD','Board Bring-up'], ARRAY['IoT','Kamera','Sikkerhet'], 15, 'Oslo', 'Senior embedded-profil med tung erfaring fra komplekse produkter (kamera/IoT) og sikkerhet. Sterk på arkitektur, ytelse, release/infrastruktur og teamledelse.', 1),
('Lars Rudolfsen', NULL, NULL, ARRAY['Autonomi','Regulering','STM32','FreeRTOS','CANopen','Embedded Linux'], ARRAY['Robotikk','Autonomi','Industri'], 8, 'Oslo', 'Kybernetikk/robotikk-ingeniør med erfaring fra sanntidsstyring og integrasjon i komplekse systemer. Spiss på regulering, sensorer og robust embedded kommunikasjon.', 2),
('Ida Abrahamsson', NULL, NULL, ARRAY['Embedded','FreeRTOS','CANopen','IoT','AWS','C/C++'], ARRAY['IoT','Automasjon','Robotikk'], 10, 'Oslo', 'Senior embedded- og kontrollsystemingeniør med bred erfaring fra IoT, automasjon og robotikk. Leverer prototyper og produksjonsklare løsninger med struktur og driv.', 3),
('Trine Ø. Olsen', NULL, NULL, ARRAY['Defence','C2','RTOS','Sensor Fusion','Networking','Robust Systems'], ARRAY['Forsvar','Sikkerhet','Taktiske systemer'], 10, 'Østlandet', 'Embedded-ingeniør med erfaring fra forsvar og sikkerhetskritiske systemer (C2, sensorer, taktiske nett). Sterk på robusthet, integrasjon og systemer som må fungere i krevende miljø.', 4),
('Tom Erik Lundesgaard', NULL, NULL, ARRAY['Embedded','Bare-metal','Zigbee','Test/Debug','Electronics','Subsea'], ARRAY['Forsvar','MedTech','Subsea'], 20, 'Oslo', 'Senior embedded-ingeniør med lang fartstid fra forsvar, medtech og subsea. Praktisk sterk på feilsøking, RF/kommunikasjon og samspillet SW–HW.', 5),
('Karl Eirik Bang Fossberg', NULL, NULL, ARRAY['Robotics','RTOS','Embedded Linux','Qt','IoT','CI/CD'], ARRAY['Robotikk','Industri','IoT'], 12, 'Oslo', 'Senior embedded med dokumentert leveranse i robotsystemer og industrielle løsninger. Kombinerer arkitektur, motor/sensor-integrasjon og DevOps for raske og stabile leveranser.', 6),
('Rikke Solbjørg', NULL, NULL, ARRAY['MedTech','Yocto','Embedded Linux','Verification','CI/CD','TDD'], ARRAY['MedTech','Regulert utvikling'], 10, 'Oslo', 'Senior embedded-profil med erfaring fra regulert medisinsk utvikling og høy kvalitet. Sterk på Yocto, testdrevet utvikling, automasjon og risikoreduserende engineering.', 7),
('Anders Larsen', NULL, NULL, ARRAY['C++','Qt','Embedded Linux','Leadership','Graphics','Developer Tooling'], ARRAY['Plattform','Grafikk/3D','Produktutvikling'], 15, 'Oslo', 'Senior C++/Qt med ledelseserfaring og produktutvikling i skalerbare team. Solid på plattform, verktøy og robuste applikasjoner – også grafikk/3D ved behov.', 8),
('Trond Hübertz Emaus', NULL, NULL, ARRAY['Rust','C++','Architecture','Embedded','CMake/Conan','System Design'], ARRAY['Embedded','Plattform','Systemarkitektur'], 12, 'Oslo', 'Arkitektursterk systemutvikler som bygger fundament og mønstre som øker teamhastighet. Bred bakgrunn fra embedded og plattformnære systemer.', 9),
('Christian Steffen Poljac', NULL, NULL, ARRAY['Security','TrustZone','RTOS','Firmware','Zephyr','ISO15118'], ARRAY['EV/Charging','Halvleder','Sikkerhet'], 10, 'Oslo', 'Senior embedded med tydelig sikkerhetsprofil (TrustZone, fuzzing, hardening) og erfaring fra EV/charging og SoC. Leverer robust, testbar firmware med høy kvalitet.', 10),
('Martin Tysseland', NULL, NULL, ARRAY['Embedded Linux','Yocto','C++','CI/CD','Docker','Systems'], ARRAY['Produktutvikling','DevOps','Embedded'], 8, 'Oslo', 'Embedded Linux/Yocto-utvikler med erfaring fra produktutvikling og drift/byggkjeder. God på helhet fra device-image til applikasjon og automasjon.', 11),
('Mattis Asp', NULL, NULL, ARRAY['Embedded','Systems','C/C++','Architecture','Integration'], ARRAY['Embedded','Systemintegrasjon'], 10, 'Oslo', 'Erfaren systemutvikler med bred embedded-kompetanse og evne til å levere robuste løsninger.', 12);
